services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: garoca_db
      POSTGRES_USER: garoca_user
      POSTGRES_PASSWORD: garoca_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn library_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_DB: garoca_db
      POSTGRES_USER: garoca_user
      POSTGRES_PASSWORD: garoca_pass
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: 'True'
      SECRET_KEY: changeme-in-production

volumes:
  postgres_data: 