# Generated by Django 4.1 on 2024-10-10 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitor',
            name='status',
        ),
        migrations.AddField(
            model_name='leitor',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='leitor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='leitor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='leitor',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='devolucao',
            field=models.DateTimeField(help_text='Selecione uma data e hora posterior à atual', verbose_name='Data de devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Finalizado')], default='in_progress', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='codigo',
            field=models.CharField(max_length=15, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.BooleanField(choices=[(True, 'Disponível'), (False, 'Indisponível')], default=True, verbose_name='Status'),
        ),
    ]
