# Generated by Django 4.1 on 2024-10-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_leitor_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
