# Generated by Django 4.2.16 on 2025-05-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_leitor_ativo_alter_leitor_criado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='livros/capas/', verbose_name='Capa do Livro'),
        ),
    ]
